version: '3'

services:
  jenkins:
    image: kwk1602/jenkins
    container_name: 'jenkins_docker'
    restart: always
    ports:
      - '58080:8080'
      - '50001:50000'
    volumes:
      - '/media/sf_JenkinsServerRepo/PrivateWorkspace:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      TZ: "Asia/Seoul"
      PYTHONUNBUFFERED: 0